PyinfraOperation: Put *args first so that mypy correctly handles inner operation args
This is not a mypy issue - unnamed arguments are passed in order so if
PyinfraOperation were a real class instead of a protocol then
PyinfraOperation.__call__("a", "b") would pass "a" and "b" to _sudo and
_sudo_user.

This is the minimum fix to avoid errors like these:

pyinfra_deploy.py:6: error: Too few arguments for "__call__" of "PyinfraOperation"  [call-arg]
pyinfra_deploy.py:7: error: Argument 1 to "__call__" of "PyinfraOperation" has incompatible type "str"; expected "bool"  [arg-type]